name: SupervisedArduino

services:
  node-red:
    env_file: "node-red/dev.env"
  # broker:
  #   container_name: SupervisedArduino-broker
  #   image: eclipse-mosquitto:latest
  #   ports:
  #     - 1883:1883
  #   networks:
  #     - SupervisedArduino-net
  #   volumes:
  #     - mosquitto-data:/mosquitto/data
  #     - mosquitto-log:/mosquitto/log
  #     - ./broker/mosquitto-dev.conf:/mosquitto/config/mosquitto.conf

volumes:
  mosquitto-data:
    name: SupervisedArduino-mosquitto-data
  mosquitto-log:
    name: SupervisedArduino-mosquitto-log
    
networks:
  SupervisedArduino-net: