# Find and replace "SupervisedArduino" with your project name
name: SupervisedArduino

services:
  # db:
  #   container_name: SupervisedArduino-db
  #   build: ./db
  #   env_file:
  #     - stack.env
  #   volumes:
  #     - ./db_data:/var/lib/postgresql/data
  #   networks:
  #     - SupervisedArduino-net
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
  #     interval: 2s
  #     timeout: 1s
  #     retries: 10
  
  # db-manager:
  #   container_name: SupervisedArduino-db-manager
  #   build: ./db-manager
  #   env_file:
  #     - stack.env
  #   volumes:
  #     # Example changelog is in db-manager/changelog - update per application needs
  #     - ./db-manager/changelog:/liquibase/changelog
  #   networks:
  #     - SupervisedArduino-net
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #       restart: true
  #   command: 
  #     - --classpath=/liquibase/changelog
  #     - --changeLogFile=root.yaml
  #     - --url=jdbc:postgresql://db:5432/postgres
  #     - --username=${POSTGRES_USER}
  #     - --password=${POSTGRES_PASSWORD}
  #     - --logLevel=debug
  #     - update

  node-red:
    container_name: SupervisedArduino-nodered
    build: ./node-red
    ports:
      - "${NODE_RED_PORT:-1880}:1880"
    volumes:
      - node-red-data:/data
      - ./node-red/settings.js:/data/settings.js
    networks:
      - SupervisedArduino-net
    env_file: 
      - "node-red/prod.env"
      - "stack.env"
    devices:
      - "COM5:/dev/ttyS0"
      - "COM6:/dev/ttyS1"

volumes:
  node-red-data:
    name: SupervisedArduino-data

networks:
  SupervisedArduino-net: