# Select the base image, specify a specific version of the image before going to production!
FROM liquibase:latest
# FROM liquibase:4.29
# FROM liquibase:4.29-alpine
# https://hub.docker.com/_/liquibase
